import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import api, { imageUrl } from '../services/api';
import { useAuth } from '../context/AuthContext';

export default function BuyerMarketplace() {
  const { user } = useAuth(); const navigate = useNavigate();
  const [products, setProducts] = useState([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const loadProducts = async () => { setLoading(true); setError(''); try { const response = await api.get('/products', { params: { search } }); setProducts(response.data); } catch (requestError) { setProducts([]); setError(requestError.response?.data?.message || 'Unable to load products. Please try again.'); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(loadProducts, 200); return () => clearTimeout(timer); }, [search]);
  const addToCart = (product) => { const cart = JSON.parse(localStorage.cart || '[]'); const item = cart.find((cartItem) => cartItem._id === product._id); if (item) item.cartQuantity += 1; else cart.push({ ...product, cartQuantity: 1 }); localStorage.cart = JSON.stringify(cart); setNotice('Added to your cart.'); };
  const buyNow = async (product) => { try { await api.post('/orders', { products: [{ product: product._id, productName: product.productName, quantity: 1, price: product.price }], totalAmount: product.price }); setNotice('Purchase request sent to the farmer.'); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to complete purchase.'); } };
  return <main className="container py-4"><div className="d-flex justify-content-between align-items-center gap-3"><div><h1>Fresh marketplace</h1><p className="text-muted mb-0">Products listed directly by farmers.</p></div>{user?.role === 'buyer' && <div className="d-flex gap-2"><Link className="btn btn-outline-success" to="/purchases">My purchases</Link><Link className="btn btn-outline-success" to="/cart">Cart</Link></div>}</div>{notice && <div className="alert alert-success mt-3">{notice}<button className="btn-close float-end" onClick={() => setNotice('')} /></div>}<input className="form-control my-3" value={search} placeholder="Search products..." onChange={(event) => setSearch(event.target.value)} />{error && <div className="alert alert-danger d-flex justify-content-between align-items-center gap-3"><span>{error}</span><button className="btn btn-sm btn-outline-danger" onClick={loadProducts}>Retry</button></div>}{loading ? <p className="text-muted">Loading fresh products...</p> : !error && <div className="row g-4">{products.map((product) => <div className="col-md-4" key={product._id}><article className="card h-100 shadow-sm">{product.image ? <img src={imageUrl(product.image)} className="card-img-top" style={{ height: 210, objectFit: 'cover' }} alt={product.productName} /> : <div className="card-img-top d-grid place-items-center bg-light text-muted" style={{ height: 210 }}>No photo</div>}<div className="card-body d-flex flex-column"><span className="small text-success">{product.category}</span><h5>{product.productName}</h5><p className="text-muted small flex-grow-1">{product.description}</p><strong>Rs. {product.price}/unit</strong><p className="small mb-3">By {product.farmer?.name || 'Farmer'} · {product.quantity} available</p><div><Link className="btn btn-sm btn-outline-success me-2" to={`/products/${product._id}`}>Details</Link>{user?.role === 'buyer' && <><button className="btn btn-success btn-sm me-2" onClick={() => buyNow(product)}>Buy now</button><button className="btn btn-outline-success btn-sm" onClick={() => addToCart(product)}>Cart</button></>}</div></div></article></div>)}</div>}{!loading && !error && !products.length && <p className="text-muted">No products have been listed yet.</p>}</main>;
}
